### ISSUE TITLE
Branches

### ISSUE THREAD

**Issue by KarKunze** [bootcamp-s18/pac-man#4]
Evaluate unmerged branches.

**Comment by rcbrowder** [comment]
I'm starting to work on reviewing the original project's unmerged branches.

**Comment by rcbrowder** [comment]
I took the changes from Christian and Dimitri's `develop` and `ghost-stuff` branches in their original project and implemented them in my `ghost-movement` branch. I will close this issue as soon as that pull request is reviewed and merged.

**Comment by rcbrowder** [comment]
Branch merged.
